#1397: Command to delete excess backup videos and reorder versions
Signbank/Global-signbank pull request #1398
Opened 2024-11-26 14:25 UTC by susanodd

2024-11-27 16:17 UTC, vanlummelhuizen commented
@susanodd Thank you for this PR and making it not too big. I can see it does not do anything, but I assume it should do something in the future. I guess you first want to see that it is outputting the correct stuff before letting it (re)move and rename files.

Although the PR itself is not big, the functions you wrote are a bit long and sometimes hard to follow. I think there are several places where you could improve this. In function *remove_backups*:

* You can get a distinct set of glosses with `distinct_glosses = Gloss.objects.filter(glossvideo__in=queryset).distinct()` instead of 

```python
    glosses_in_queryset = [obj.gloss for obj in queryset]
    distinct_glosses = list(set(glosses_in_queryset))
```

Also, move that statement to the place where it is used.

* You could  get rid of the `if obj.version == 0:` clause if you do `queryset = queryset.filter(version__gt=0)`.

* This code:
```python
    lookup_backup_files = dict()
    for gloss in distinct_glosses:
        lookup_backup_files[gloss] = GlossVideo.objects.filter(gloss=gloss, version__gt=0).order_by('version', 'id')
    for gloss, videos in lookup_backup_files.items():
```
could be reduced to
```python
    for gloss in distinct_glosses:
        videos = GlossVideo.objects.filter(gloss=gloss, version__gt=0).order_by('version', 'id')
```

* There are ways of reducing the `if DEBUG_VIDEOS:` clauses to one line if there is only a print statement. E.g something like `print('bla') if DEBUG_VIDEOS else None`.

* Because there are two steps, move each step to a separate function.

2024-11-28 05:52 UTC, susanodd commented
The improvements are much welcome!

That the code seems in the wrong place has to do with it being evolved several times. I wanted to show the non-backup videos as well in the print statements to look at them as well. The glosses need to be retrieved from the selected GlossVideo objects before anything is deleted.

I will split it into several commands, functions. I'm trying to ascertain how to make it the most useful to clean up the objects.
The admin facilities can either do commands on selected objects or queries / filters. I can try making a filter on the type of video file.

The API does not check the video type. That is done in the browser when you select a file. I wanted to check the webm video type but I can't upload it on Safari. But for some reason, there are webm videos from the API. I had to copy locally a webm file onto an already existing backup file in order to check that it can change the name correctly.

Probably we need some conversion commands, too, in the admin. It is much easier to navigate to files here than on Ubuntu.

2024-11-28 08:11 UTC, vanlummelhuizen commented
> The glosses need to be retrieved from the selected GlossVideo objects before anything is deleted.

You are right.

2024-11-29 11:45 UTC, susanodd commented
@vanlummelhuizen I added a column to the GlossVideo table in the admin. It shows the "file type" (that returned by "file".)

Lots of the "mp4" files are actually Apple iTunes Video (.M4V) Video. So they should be ".mp4" ?

The conversion "ensure_mp4" was checking for h264 for a very long time and just making them be mp4.

2024-11-29 12:20 UTC, susanodd commented
Regarding the requests for code improvement

- There are ways of reducing the if DEBUG_VIDEOS: clauses to one line if there is only a print statement. E.g something like print('bla') if DEBUG_VIDEOS else None.

I prefer not to do this, since it makes it difficult to skip over lines because of lack of indentation.

The other changes I have made.

2025-01-23 11:04 UTC, susanodd commented
On signbank-susan, the database is from 20 januari.

@vanlummelhuizen @Woseseltops 

What do you guys think of hiding the "commands" and just merging the "new columns" with master? Those are just read only.
It's possible to filter on wrong filenames.
(It's only one line of code to hide the commands (temporarily until approved).

2025-02-03 15:00 UTC, susanodd commented
I added high priority to this issue because there are still lots of NME videos that point to the normal video, even after they were re-uploaded.
 
This issue has a filter on NME video as well as "wrong filename".

I put the most recent database on signbank-susan, where this branch is.
And did the search there. To my surprise, the videos are still messed up. (https://github.com/Signbank/Global-signbank/issues/1453#issuecomment-2631050655)
It's not possible to "witness" whether the videos are fixed or not.

2025-02-14 16:10 UTC, Woseseltops requested changes
I like this initiative, although it's not 100% clear to me how the commands should be used. Perhaps you can create a page on the wiki for it, along with some examples of what will happen? Let me know if you have something, I will try to organize it for you :)

About code style, I have quite a few smaller stylistic things this time. Don't get discouraged by this! It's all small stuff.

2025-02-14 16:10 UTC, Woseseltops commented on signbank/video/admin.py
> +def remove_backups(modeladmin, request, queryset):
Alternative suggestion: instead of deleting, move them to an archive location that we can manually empty later.

2025-02-14 16:10 UTC, Woseseltops commented on signbank/video/admin.py
> +            # remove the video file so the GlossVideo object can be deleted
I'd prefer this as guard clause

2025-02-14 16:10 UTC, Woseseltops commented on signbank/video/admin.py
> +    # this is a patch for repairing doubly linked files
Let's make this a doscstring.

2025-02-14 16:10 UTC, Woseseltops commented on signbank/video/admin.py
> +
Here too I feel it would make more sense to return `None` or raise an error

2025-02-17 08:25 UTC, susanodd commented on signbank/video/convertvideo.py
> +        return ''
See above.

We had a problem that some videos ended up in the wrong folder.
The check on 'glossvideo' is to check this.

We want to prevent that a file existence test is checking for the existence of a prefix

(The path is constructed by putting "writable" at the front of the relative path stored in the gloss video object.
So the first is to avoid an existence test on "....writable/" (without any actual video)

I'll document the cases of what it's meant to be testing.

I made it be empty because it can also test whether it's empty by the caller. (More or less the same as an error.)

2025-02-17 08:28 UTC, susanodd commented on signbank/video/models.py
> +        except (PermissionError, OSError):
That's true. I've been running the code with DEBUG_VIDEOS turned on.

There are actually lots of expressions such as this that involve the file system.

2025-02-17 08:29 UTC, susanodd commented on signbank/video/admin.py
> +        return False
I don't think it returns a Boolean?

2025-02-17 08:32 UTC, susanodd commented on signbank/video/admin.py
> +        file_exists = tuple((b, b) for b in ('True', 'False'))
Okay, I need to figure out how to do that.

(It's passing the query around that is done by Django Admin. I had trouble with it forgetting the query. I made it explicit everywhere.)

2025-02-17 08:33 UTC, susanodd commented on signbank/video/admin.py
> +            from pathlib import Path
There is some confusion about the circular imports. PyCharm flags stuff.

2025-02-17 08:39 UTC, susanodd commented on signbank/video/admin.py
> +
I'm pretty sure this was for type-checking. Empty string is also of type string.

By the way, here is an existence test that makes use of str(obj.videofile).
If that is empty, it's merely checking whether WRITABLE_FOLDER exists.

That's why all of those tests are there here, and above.

2025-02-17 13:32 UTC, vanlummelhuizen commented on signbank/video/admin.py
> +        return False
Just FYI: if you want to fully match a string, you could use `re.fullmatch` (see also https://docs.python.org/3/library/re.html#search-vs-match). And if you want True if there is a match and False there is none, cast it to a boolean with `bool()`. Then it becomes:

```python
return bool(re.fullmatch(r".+-(\d+)_(nme_\d+|nme_\d+_left|nme_\d+_right)$", filename_without_extension))
```

Again just FYI, the changes @susanodd made per review are clean enough.

2025-02-18 11:29 UTC, susanodd commented
Points

- the code was developed on development servers and locally. No video files. The code was made so that it can run without files.

2025-03-13 09:15 UTC, Woseseltops commented
Final request: make the documentation shorter, without losing information

Examples

Before
```python
 # The function is only called if there is no file; the filename does not match any correct pattern, the extension does not match any video file type, and this allows the function to work on the development servers.
```

After
```python
# Only runs if no file exists and the filename is invalid, ensuring compatibility with dev servers.
```

Before
```python
# this is only for documentation purposes in the patterns, it's not a setting
# these were found to work properly on Ubuntu and match older files and older code
```

After
```python
# Documentation-only; works on Ubuntu and matches older files/code.  
```

2025-03-14 09:35 UTC, merged